<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category' => 'Earrings',
                'name' => 'Emerald Drop Earrings',
                'short_description' => 'Premium Alloy · Hypoallergenic · Elegant Drop Design',
                'description' => "BloomShine Emerald Drop Earrings feature stunning green gemstone replicas set in premium anti-tarnish alloy. Each pair is meticulously crafted to capture the elegance of real emeralds while remaining lightweight and comfortable for all-day wear.\n\nPerfect for festive occasions or everyday sophistication, these earrings blend luxury with affordability.",
                'price' => 399,
                'original_price' => null,
                'tags' => ['Earrings', 'Green Stones', 'Festive'],
                'badge' => 'bestseller',
                'rating' => 4.8,
                'review_count' => 124,
                'image_emoji' => '💎',
                'image_bg' => 'linear-gradient(145deg,#E8F5E9,#C8E6C9)',
                'image_bottle' => 'linear-gradient(160deg,#2E7D32,#1B5E20)',
                'details' => ['Material Quality' => 'Premium Alloy with anti-tarnish coating', 'Finish Type' => 'Hypoallergenic - suitable for sensitive skin', 'Design Style' => 'Elegant drop design with emerald-colored stones'],
                'care_instructions' => ['Avoid prolonged water exposure and harsh chemicals', 'Clean gently with a soft, dry cloth', 'Store in a cool, dry place away from sunlight', 'Keep in original box or jewelry pouch'],
            ],
            [
                'category' => 'Necklaces',
                'name' => 'Gold Plated Pendant Necklace',
                'short_description' => 'Gold Plating · Long Chain · Statement Pendant',
                'description' => "BloomShine Gold Plated Pendant Necklace showcases an elegant statement design in lustrous gold plating. The long chain allows for versatile styling, and the carefully crafted pendant makes it a perfect addition to both traditional and contemporary wardrobes.",
                'price' => 549,
                'original_price' => 699,
                'tags' => ['Necklaces', 'Gold', 'Pendant'],
                'badge' => 'sale',
                'rating' => 4.9,
                'review_count' => 210,
                'image_emoji' => '👑',
                'image_bg' => 'linear-gradient(145deg,#FFF8E1,#FFE082)',
                'image_bottle' => 'linear-gradient(160deg,#F57F17,#E65100)',
                'details' => ['Material Quality' => 'Gold plated over premium alloy base', 'Finish Type' => 'Lustrous gold plating with anti-tarnish protection', 'Design Style' => 'Statement pendant with long chain design'],
                'care_instructions' => ['Avoid chlorine and saltwater exposure', 'Remove before swimming or bathing', 'Wipe gently with a soft cloth after wearing', 'Store separately to prevent tangling'],
            ],
            [
                'category' => 'Bracelets',
                'name' => 'Pearl Beaded Bracelet',
                'short_description' => 'Faux Pearl · Elastic Band · Adjustable Fit',
                'description' => "BloomShine Pearl Beaded Bracelet combines timeless elegance with modern comfort. Featuring faux pearl beads strung on a durable elastic band, this bracelet offers an adjustable fit for all wrist sizes and works beautifully for both casual and formal occasions.",
                'price' => 299,
                'original_price' => null,
                'tags' => ['Bracelets', 'Pearls', 'Casual'],
                'badge' => null,
                'rating' => 4.7,
                'review_count' => 89,
                'image_emoji' => '✨',
                'image_bg' => 'linear-gradient(145deg,#F5F5F5,#E0E0E0)',
                'image_bottle' => 'linear-gradient(160deg,#9E9E9E,#616161)',
                'details' => ['Material Quality' => 'Faux pearl beads with elastic string', 'Finish Type' => 'Glossy pearl finish with natural shimmer', 'Design Style' => 'Beaded design with adjustable elastic band'],
                'care_instructions' => ['Keep away from extreme heat and moisture', 'Avoid direct contact with perfumes and lotions', 'Gently clean with a soft, damp cloth', 'Let air dry completely before storing'],
            ],
            [
                'category' => 'Rings',
                'name' => 'Diamond Solitaire Ring',
                'short_description' => 'Crystal Stone · Silver Finish · All Sizes Available',
                'description' => "BloomShine Diamond Solitaire Ring features a brilliant crystal stone replica in a timeless solitaire setting. Crafted in premium anti-tarnish alloy with a perfect silver finish, this ring captures the elegance and sparkle of a real diamond at a fraction of the cost.",
                'price' => 449,
                'original_price' => 599,
                'tags' => ['Rings', 'Diamond Style', 'Wedding'],
                'badge' => 'new',
                'rating' => 4.9,
                'review_count' => 67,
                'image_emoji' => '💍',
                'image_bg' => 'linear-gradient(145deg,#ECEFF1,#B0BEC5)',
                'image_bottle' => 'linear-gradient(160deg,#455A64,#263238)',
                'details' => ['Material Quality' => 'Premium alloy with crystal stone replica', 'Finish Type' => 'Silver finish with anti-tarnish coating', 'Design Style' => 'Timeless solitaire design'],
                'care_instructions' => ['Remove during bathing and swimming', 'Keep away from harsh soaps and chemicals', 'Store in a ring box to prevent scratching', 'Clean with a soft, damp cloth when needed'],
            ],
            [
                'category' => 'Bangles',
                'name' => 'Multicolor Stone Bangles',
                'short_description' => 'Rainbow Crystals · Set of 6 · Vibrant Colors',
                'description' => "BloomShine Multicolor Stone Bangles bring vibrant colors to your wrist with this stunning set of six bangles, each featuring different colored crystal replicas. Each bangle is crafted in premium alloy with a high-polish finish for maximum sparkle and durability.",
                'price' => 699,
                'original_price' => null,
                'tags' => ['Bangles', 'Colorful', 'Sets'],
                'badge' => 'bestseller',
                'rating' => 4.8,
                'review_count' => 145,
                'image_emoji' => '🌟',
                'image_bg' => 'linear-gradient(145deg,#F3E5F5,#E1BEE7)',
                'image_bottle' => 'linear-gradient(160deg,#7B1FA2,#4A148C)',
                'details' => ['Material Quality' => 'Premium alloy bangles with colored crystals', 'Finish Type' => 'High-polish finish for maximum sparkle', 'Design Style' => 'Set of 6 colorful stackable bangles'],
                'care_instructions' => ['Avoid wearing while sleeping or exercising', 'Remove before swimming or water activities', 'Wipe regularly with a soft cloth', 'Store separately to maintain shine'],
            ],
            [
                'category' => 'Anklets',
                'name' => 'Beaded Anklet with Charms',
                'short_description' => 'Colorful Beads · Adjustable · Trendy Design',
                'description' => "BloomShine Beaded Anklet with Charms features a playful mix of colorful beads and delicate charms, perfect for adding a trendy touch to your summer looks. The adjustable design ensures a comfortable fit, and the lightweight construction makes it perfect for everyday wear.",
                'price' => 259,
                'original_price' => null,
                'tags' => ['Anklets', 'Charms', 'Summer'],
                'badge' => null,
                'rating' => 4.6,
                'review_count' => 78,
                'image_emoji' => '🦶',
                'image_bg' => 'linear-gradient(145deg,#E0F2F1,#B2DFDB)',
                'image_bottle' => 'linear-gradient(160deg,#00695C,#004D40)',
                'details' => ['Material Quality' => 'Colorful beads with delicate metal charms', 'Finish Type' => 'Vibrant, lightweight design', 'Design Style' => 'Trendy beaded anklet with charm accents'],
                'care_instructions' => ['Keep away from prolonged sun exposure', 'Remove before water activities', 'Gently clean with a soft brush', 'Store in a cool, dark place'],
            ],
            [
                'category' => 'Sets',
                'name' => 'Royal Bridal Set',
                'short_description' => 'Complete Bridal Look · Necklace + Earrings + Tikka',
                'description' => "BloomShine Royal Bridal Set is a complete wedding jewelry solution featuring a coordinated necklace, earrings, and tikka in stunning crystal and pearl designs. Perfect for bridal events or festive celebrations, this set ensures you look radiant and coordinated.",
                'price' => 1299,
                'original_price' => 1599,
                'tags' => ['Sets', 'Bridal', 'Wedding'],
                'badge' => 'sale',
                'rating' => 4.9,
                'review_count' => 156,
                'image_emoji' => '🎁',
                'image_bg' => 'linear-gradient(145deg,#FCE4EC,#F8BBD0)',
                'image_bottle' => 'linear-gradient(160deg,#C2185B,#880E4F)',
                'details' => ['Material Quality' => 'Premium alloy with crystal and pearl replicas', 'Finish Type' => 'Luxurious bridal finish', 'Design Style' => 'Complete 3-piece bridal jewelry set'],
                'care_instructions' => ['Handle with care to preserve delicate details', 'Remove immediately after wearing', 'Store in separate compartments', 'Clean gently with a specialized jewelry cleaner'],
            ],
            [
                'category' => 'Brooches',
                'name' => 'Vintage Floral Brooch',
                'short_description' => 'Detailed Flower Design · Gold Finish · Classic Style',
                'description' => "BloomShine Vintage Floral Brooch brings timeless elegance to any outfit with its intricate flower design and classic gold finish. Perfect for pinning on scarves, lapels, or bags, this brooch adds a sophisticated touch to both traditional and modern looks.",
                'price' => 349,
                'original_price' => 449,
                'tags' => ['Brooches', 'Vintage', 'Accessories'],
                'badge' => 'new',
                'rating' => 4.7,
                'review_count' => 52,
                'image_emoji' => '🌹',
                'image_bg' => 'linear-gradient(145deg,#FFF3E0,#FFE0B2)',
                'image_bottle' => 'linear-gradient(160deg,#E65100,#BF360C)',
                'details' => ['Material Quality' => 'Premium alloy with gold plating', 'Finish Type' => 'Vintage-inspired gold finish', 'Design Style' => 'Intricate floral design with vintage charm'],
                'care_instructions' => ['Store with a safety pin cover', 'Avoid frequent pinning and unpinning', 'Wipe with a soft cloth regularly', 'Keep away from humidity and extreme temperatures'],
            ],
        ];

        foreach ($products as $p) {
            $category = Category::where('name', $p['category'])->first();
            if (!$category) continue;

            Product::create([
                'category_id' => $category->id,
                'name' => $p['name'],
                'slug' => Str::slug($p['name']),
                'price' => $p['price'],
                'original_price' => $p['original_price'],
                'description' => $p['description'],
                'short_description' => $p['short_description'],
                'image' => json_encode([
                    'emoji' => $p['image_emoji'],
                    'bg' => $p['image_bg'],
                    'bottle' => $p['image_bottle'],
                ]),
                'tags' => json_encode($p['tags']),
                'details' => isset($p['details']) ? json_encode($p['details']) : json_encode([]),
                'care_instructions' => isset($p['care_instructions']) ? json_encode($p['care_instructions']) : json_encode([]),
                'badge' => $p['badge'],
                'rating' => $p['rating'],
                'review_count' => $p['review_count'],
                'status' => 'active',
            ]);
        }
    }
}
